version: '3'
services:
  web:
    restart: unless-stopped
    build: .
    depends_on:
      - redis
      - postgres
    environment:
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_NAME: sentry
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_SECRET_KEY: sentry-secret-key
      SENTRY_SYSTEM_URL_PREFIX: https://sentry.example.com
    volumes: #For å alternativt kunne lese env variabler på samme måte som vault
      - ./vault:/var/run/secrets/nais.io/vault
    ports:
      - '9000:9000'

  redis:
    restart: unless-stopped
    image: redis

  postgres:
    restart: unless-stopped
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: sentry
      POSTGRES_DB: sentry
      POSTGRES_PASSWORD: sentry