version: '3'
services:
  redis:
    restart: unless-stopped
    image: redis

  postgres:
    restart: unless-stopped
    image: postgres:9.5
    ports:
      - '5432:5432'
  web:
    restart: unless-stopped
    build: .
    depends_on:
      - redis
      - postgres
    environment:
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
    volumes:
      - ./vault:/var/run/secrets/nais.io/vault
    ports:
      - '9000:9000'