apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: dataplattform
  name: sentry-proxy
  namespace: default
spec:
  image: repo.adeo.no:5443/sentry-proxy:RELEASE_VERSION
  port: 8043
  team: dataplattform
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: /health/isReady
    initialDelay: 10
    timeout: 1
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 100
  resources:
    limits:
      cpu: 500m
      memory: 64Mi
    requests:
      cpu: 200m
      memory: 32Mi
  ingresses:
   - "https://sentry.nav.no"
  logformat: accesslog
  logtransform: dns_loglevel
  webproxy: false
  vault:
    enabled: true
  env:
  - name: APP_VERSION
    value: "RELEASE_VERSION"
  - name: SENTRY_INTERNAL_URL
    value: https://sentry.nais.adeo.no

