apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamforeldrepenger
  name: sentry-proxy
  namespace: default
spec:
  image: repo.adeo.no:5443/sentry-proxy:RELEASE_VERSION
  port: 8043
  team: teamforeldrepenger
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: /health/isReady
    initialDelay: 10
    timeout: 1
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 100
  resources:
    limits:
      cpu: 500m
      memory: 64Mi
    requests:
      cpu: 200m
      memory: 32Mi
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
   - "https://sentry.nav.no"
  logformat: accesslog # Optional. The format of the logs from the container if the logs should be handled differently than plain text or json
  logtransform: dns_loglevel # Optional. The transformation of the logs, if they should be handled differently than plain text or json
  webproxy: false # Optional. Expose web proxy configuration to the application using the HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables.
  vault:
    enabled: true
  env:
  - name: APP_VERSION
    value: "RELEASE_VERSION"
  - name: APP_NAME
    value: sentry-proxy

