version: '3'
services:
  nginx:
    restart: unless-stopped
    build: .
    environment:
      GATEWAY_URL: http://echo-server
    ports:
      - '8043:8043'
  echo-server:
    image: mendhak/http-https-echo

