apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamforeldrepenger
  name: sentry-redis
  namespace: default
spec:
  image: redis:alpine
  port: 6379
  team: teamforeldrepenger
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  istio:
    enabled: false
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  webproxy: false
  secrets: false